---

- include: Debian_install.yml
  when: ansible_os_family == 'Debian'

- name: Enable nginx
  service:
    name: nginx
    enabled: yes
    state: started

- include: letsencrypt.yml
  when: nginx_site_use_ssl and nginx_site_use_letsencrypt

- include: site.yml
